import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.DatabaseMetaData;
import java.util.*;

public class derby {
	private static String driver = "org.apache.derby.jdbc.ClientDriver";
	private static String protocol = "jdbc:derby://localhost:1527/";
	String dbName = "URLCollection";

	private PreparedStatement psInsert = null;
	private PreparedStatement psDelete = null;
	private Statement s = null;
	private ResultSet rs = null;
	private Connection conn = null;

	public String[] doIt() {

		String[] URls = new String[3];

		for (int i = 0; i < 3; i++) {
			URls[i] = " ";
		}

		try {
			Class.forName(driver).newInstance();
			System.out.println("Loaded the appropriate driver");
		} catch (Exception e) {
			e.printStackTrace();
		}

		System.out.println(" application starting...........");

		try {
			conn = DriverManager.getConnection(protocol + dbName
					+ ";create=true");
			System.out.println("Connected to and created database " + dbName);

			DatabaseMetaData dmd = conn.getMetaData();
			ResultSet rs = dmd.getTables(null, null, "URLS", null);

			if (rs.next()) {
				System.out.println(" URLs already exists");
				s = conn.createStatement();
			} else {
				s = conn.createStatement();

				s.execute("create table URLs(ID integer primary key generated by default as identity , URL varchar(40),Time DATE)");
				System.out.println("Created table 'URLs'");
			}

			java.util.Date utilDate = new java.util.Date();
			java.sql.Date date = new java.sql.Date(utilDate.getTime());

			psInsert = conn
					.prepareStatement("insert into URLs  (URL,Time) values(?, ?)");

			psInsert.setString(1, "www.google.com");
			psInsert.setDate(2, date);
			psInsert.executeUpdate();
			System.out.println("Inserted " + "www.google.com" + " " + date);

			psInsert.setString(1, "www.baidu.com");
			psInsert.setDate(2, date);
			psInsert.executeUpdate();
			System.out.println("Inserted " + "www.baidu.com" + " " + date);

			psInsert.setString(1, "www.yahoo.com");
			psInsert.setDate(2, date);
			psInsert.executeUpdate();
			System.out.println("Inserted " + "www.yahoo.com" + " " + date);

			rs = s.executeQuery("select * from URLs order by ID");
			int i = 0;
			while (rs.next()) {

				String s = rs.getString(2);
				URls[i] = s;

				System.out.print("ID:" + rs.getInt(1));
				System.out.print(" URL: " + s);
				System.out.print(" Time: " + rs.getDate(3));
				System.out.println();
				// System.out.println(URls[i]);
				i++;
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}

		
		try {
			s.execute("drop table URLs");
			System.out.println("Dropped table URLs");
			//DriverManager.getConnection("jdbc:derby:;shutdown=true");
			
				conn.close();
				conn = null;
				s.close();
				s = null;
				//rs.close();
				rs = null;

			} catch (Exception e) {
				e.printStackTrace();
			}

			// System.out.println("Shutdown Derby!");

		/*} catch (SQLException se) {
			if (((se.getErrorCode() == 50000) && ("XJ015".equals(se
					.getSQLState())))) {

				System.out.println("Derby shut down normally");

			} else {
				System.err.println("Derby did not shut down normally");
				System.err.println("\n----- SQLException -----");
				System.err.println("  SQL State:  " + se.getSQLState());
				System.err.println("  Error Code: " + se.getErrorCode());
				System.err.println("  Message:    " + se.getMessage());
			}
		}
*/
		return URls;
	}

	public static void main(String[] args) {
		derby t = new derby();
		t.doIt();

	}
}
